spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create

# DIRECT SUPABASE CONFIG (Paste your details here!)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/skill_mentor}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin12}

#DEBUG<INFO<WARN<ERROR
logging.level.root=INFO
logging.level.com.stemlink.skillmentor=DEBUG

jwt.secret=a-string-secret-at-least-256-bits-long-skillmentor
clerk.jwks.url=https://happy-crow-68.clerk.accounts.dev/.well-known/jwks.json
cors.allowed-origins=http://localhost:3000,http://localhost:3001,http://localhost:3002,http://localhost:5173,http://localhost:8080