    spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Swagger in production (optional, usually allowed for this type of projects)
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
